### ISSUE TITLE
Fix Images orientation at Sponsorship & Photography Team

### ISSUE THREAD

**Issue by AdityaBirangal** [TEDxMITAOE/TEDxMITAOE#5]
https://tedxmitaoe.github.io/TEDxMITAOE/finance.html
https://tedxmitaoe.github.io/TEDxMITAOE/socialmedia.html

**Comment by AbhishekMore-1** [comment]
Hey @AdityaBirangal,
I have raised one pull request which is solving all this errors/bugs
Pull Request - #6 
Please merged it into master branch. After reviewing, please give feedback :)
